download manifest.json in ci part

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -19,6 +19,10 @@ jobs:
         DBT_ENV_SECRET_USER_PASSWORD: ${{ secrets.DBT_ENV_SECRET_USER_PASSWORD }}
         DBT_ENV_SECRET_USER_NAME: ${{ secrets.DBT_ENV_SECRET_USER_NAME }}
         DBT_ENV_SECRET_DATABASE_NAME: ${{ secrets.DBT_ENV_SECRET_DATABASE_NAME }}
+        GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
+        GCP_PRJ_ID: ${{ secrets.GCP_PRJ_ID }}
+        GCS_BUCKET_NAME: ${{ secrets.GCP_BUCKET_NAME }}
+
 
     steps:
     - name: Checkout repository 
@@ -29,14 +33,17 @@ jobs:
       with:
         python-version: '3.9'
 
+    - name: Install dependencies
+      run: pip install -r requirements.txt
+
     - name: Set up Google Cloud SDK
       uses: google-github-actions/setup-gcloud@v0.2.0
       with:
-        service_account_key: ${{ secrets.GCP_SA_KEY }}
-        project_id: ${{ secrets.GCP_PRJ_ID }}
+        service_account_key: ${{ env.GCP_SA_KEY }}
+        project_id: ${{ env.GCP_PRJ_ID }}
 
-    - name: Install dependencies
-      run: pip install -r requirements.txt
+    - name: Get manifest file from gcs
+      run: gsutil cp -r gs://${{ env.GCS_BUCKET_NAME }}/manifest.json ./ || echo "manifest.json not found"
 
     - name: Get schema_id
       id: schema_id
